StockProject/Models/APISettings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StockProject.Models
{
	public class APISettings
	{
		public string SecretToken { get; set; }

		public APISettings(string secretToken)
		{
			SecretToken = secretToken;
		}
	}
}

StockProject/Models/Stock.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StockProject.Models
{
	public class Stock
	{
		[Key]
		[Required]
		public string Symbol { get; set; }
		[Required]
		public string CompanyName { get; set; }
		[Required]
		public string Description { get; set; }
		[Required]
		public string WebSite { get; set; }
		[Required]
		public string Country { get; set; }
		[Required]
		public double LatestPrice { get; set; }
		[Required]
		public DateTime? LastUpdate { get; set; }
		[Required]
		public double IEXOpen { get; set; }
		[Required]
		public double ChangePercent { get; set; }
	}
}

StockProject/Models/StockInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StockProject.Models
{
	public class StockInfo
	{
		public string CompanyName { get; set; }
		public string Symbol { get; set; }
		public string Description { get; set; }
		public string WebSite { get; set; }
		public string Country { get; set; }
		public double IEXOpen { get; set; }
		public double ChangePercent { get; set; }
	}
}

StockProject/Models/StockQuote.cs
using Newtonsoft.Json.Converters;
using StockProject.Services.Handlers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace StockProject.Models
{
	public class StockQuote
	{
		[JsonConverter(typeof(MicrosecondEpochConverter))]
		public DateTime LatestUpdate { get; set; }
		public double LatestPrice { get; set; }
		public double ChangePercent { get; set; }
		public double IEXOpen { get; set; }
	}
}

StockProject/Controllers/StocksApiController.cs
using Microsoft.AspNetCore.Mvc;
using StockProject.Data.Dtos;
using StockProject.Exceptions;
using StockProject.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StockProject.Controllers
{
	[ApiController]
	[Route("api/live")]
	public class StocksApiController : ControllerBase
	{
		IStockService _stockService;

		public StocksApiController(IStockService stockService)
		{
			_stockService = stockService;
		}

		[HttpGet("{symbol}")]
		public IActionResult GetStock(string symbol)
		{
			try
			{
				var dto = _stockService.GetStock(symbol);
				return Ok(dto);
			}
			catch (UnknownSymbolException)
			{
				return NotFound(null);
			}
			catch (ArgumentNullException)
			{
				return NotFound(null);
			}
		}
	}
}

StockProject/Controllers/StocksController.cs
using Microsoft.AspNetCore.Mvc;
using StockProject.Exceptions;
using StockProject.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StockProject.Controllers
{
	public class StocksController : Controller
	{
		IStockService _stockService;

		public StocksController(IStockService stockService)
		{
			_stockService = stockService;
		}

		public IActionResult Search()
		{
			return View();
		}

		public IActionResult Result(string symbol = null)
		{
			try
			{
				var dto = _stockService.GetStock(symbol);
				return View(dto);
			}
			catch (UnknownSymbolException)
			{
				return View(null);
			}
			catch (ArgumentNullException ex)
			{
				return View(null);
			}
		}
	}
}

StockProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - StockProject</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Stocks" asp-action="Search">StockProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stocks" asp-action="Search">Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - StockProject
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StockProject/Views/Stocks/Result.cshtml
@{
	ViewData["Title"] = "Result";
}
@model ReadStockDto

@{
	if (Model != null)
	{
		<h3 id="symbol" class="mx-2">@Model.Symbol</h3>
		<div class="card">
			<div class="mx-2">
				<strong>Company Name: </strong><span>@Model.CompanyName</span>
			</div>
			<div class="mx-2">
				<strong>Latest Price: </strong><span id="latestPrice">@Model.LatestPrice</span>
				<span> </span>
				<small id="changePercent">@(Model.ChangePercent * 100)%</small>
				<span> </span>
				<small id="liveSmall" class="text-danger">LIVE</small>
			</div>
			<div class="mx-2">
				<strong>Open Price: </strong><span id="openPrice">@Model.IEXOpen</span>
			</div>
			<div class="mx-2">
				<strong>Country: </strong><span>@Model.Country</span>
			</div>
			<div class="mx-2">
				<strong>Description: </strong><span>@Model.Description</span>
			</div>
			<div class="mx-2">
				<strong>WebSite: </strong><a href="@Model.WebSite">@Model.WebSite</a>
			</div>
		</div>
	}
	else
	{
		<div class="w-100 d-flex justify-content-center">
			<span>No stock found. <a asp-action="Search">Try again</a></span>
		</div>
	}
}
@section Scripts
{
	@{
		if (Model != null)
			{
				<script>
					$(function () {
						let symbol = $("#symbol").text();
						let latestPriceElement = $("#latestPrice");
						let liveSmall = $("#liveSmall");
						let changePercentSmall = $("#changePercent");
						setInterval(function () {
							$.ajax({
								global: true,
								url: `/api/live/${symbol}`,
								type: "GET",
								success: function (res) {
									latestPriceElement.text(res.latestPrice);
									changePercentSmall.text(`${res.changePercent * 100}%`)
									if (res.latestPrice > res.iexOpen) {
										if (!changePercentSmall.hasClass("text-success")) {
											changePercentSmall.addClass("text-success").removeClass("text-danger");
										}
									}
									else {
										if (!changePercentSmall.hasClass("text-danger")) {
											changePercentSmall.addClass("text-danger").removeClass("text-success");
										}
									}
									liveSmall.text(" LIVE");
								},
								error: function () {
									liveSmall.text("");
								}
							});

						}, 300000);
					})
				</script>
			}
	}
}

StockProject/Views/Stocks/Search.cshtml
@{
	ViewData["Title"] = "Search";
}
@model StockInfo

@{
	var searchToken = Guid.NewGuid().ToString();
}
<div class="form-group">
	<label class="control-label" for="">Stock symbol</label>
	<input id="inpSymbol" type="text" class="form-control" placeholder="AAPL" />
</div>
<div class="form-group">
	<a id="btnSearch" class="btn btn-success" asp-action="Result" asp-route-symbol="@searchToken">
		Search
	</a>
</div>

<script>
	window.onload = function(){
		var searchLink = document.getElementById("btnSearch");
		var originalHref = searchLink.href;
		searchLink.onclick = function(e){
			var searchTextElement = document.getElementById("inpSymbol");
			e.target.href = originalHref.replace("@searchToken", searchTextElement.value);
		};
	}
</script>